### ISSUE TITLE
tag omission

### ISSUE THREAD

**Issue by kiic-leung** [tobegit3hub/mycomputer#4]
in   /static/html/home.html  line 119  tag </ul>，you miss a '>'

 <div class="timeline-body">
          <ul class="list-unstyled">
               <li><a href="mailto:tobeg3oogle@gmail.com?Subject=mycomputer.xyz" target="_top">tobeg3oogle@gmail.com<a/></li>
               <li><a href="mailto:1427077943@qq.com?Subject=mycomputer.xyz" target="_top">1427077943@qq.com</a></li>
          </ul
 </div>

**Comment by tobegit3hub** [comment]
Thanks @kiic-leung and it's fixed by your PR :+1:
